import React from 'react';

const CombinedPDFGenerator = {
	// Generate watermark style for PDF
	getWatermarkStyle: () => {
		return `
      @media print {
        .watermark {
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          font-size: 8em;
          opacity: 0.08;
          color: #cccccc;
          pointer-events: none;
          z-index: -1;
          font-weight: 300;
          font-family: 'Arial', sans-serif;
          letter-spacing: 0.1em;
          user-select: none;
        }
        
        .watermark-multiple {
          position: fixed;
          width: 100%;
          height: 100%;
          top: 0;
          left: 0;
          pointer-events: none;
          z-index: -1;
          background-image: 
            radial-gradient(circle at 25% 25%, transparent 20px, transparent 20px),
            radial-gradient(circle at 75% 25%, transparent 20px, transparent 20px),
            radial-gradient(circle at 25% 75%, transparent 20px, transparent 20px),
            radial-gradient(circle at 75% 75%, transparent 20px, transparent 20px);
          background-size: 200px 200px;
          opacity: 0.03;
        }
        
        .watermark-multiple::before {
          content: 'QuizAI';
          position: absolute;
          top: 20%;
          left: 20%;
          transform: rotate(-45deg);
          font-size: 3em;
          color: #ddd;
          opacity: 0.5;
        }
        
        .watermark-multiple::after {
          content: 'QuizAI';
          position: absolute;
          bottom: 20%;
          right: 20%;
          transform: rotate(-45deg);
          font-size: 3em;
          color: #ddd;
          opacity: 0.5;
        }
      }
      
      @media screen {
        .watermark {
          display: block;
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          font-size: 6em;
          opacity: 0.05;
          color: #999;
          pointer-events: none;
          z-index: -1;
          font-weight: 300;
          font-family: 'Arial', sans-serif;
        }
      }
    `;
	},

	// Generate Combined PDF (Quiz + Answer Key)
	generate: async (quizData, questions) => {
		const quizTitle = (quizData?.title || 'Quiz Sheet').toUpperCase();
		const date = new Date().toLocaleDateString();

		const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${quizTitle} - Complete</title>
        <style>
          ${CombinedPDFGenerator.getWatermarkStyle()}
          @media print { 
            @page { 
              margin: 1in; 
              @bottom-center {
                content: "Generated by QuizAi - ${new Date().toLocaleDateString()}";
                font-size: 10pt;
                color: #888;
              }
            }
            .page-break { page-break-before: always; }
          }
          body { 
            font-family: 'Arial', sans-serif; 
            line-height: 1.6; 
            color: #333; 
            max-width: 100%; 
            margin: 0; 
            padding: 20px;
            position: relative;
          }
          .watermark {
            display: block;
          }
          .header { 
            text-align: center; 
            margin-bottom: 30px; 
            border-bottom: 2px solid #3f51b5;
            padding-bottom: 15px;
          }
          .title { 
            font-size: 28px; 
            font-weight: bold; 
            margin-bottom: 10px;
            color: #3f51b5;
          }
          .answer-key-title {
            color: #d32f2f;
          }
          .info { 
            font-size: 16px; 
            margin: 8px 0;
            color: #555;
          }
          .instructions {
            background: #f0f4ff;
            border: 1px solid #c5cae9;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
          }
          .question { 
            margin: 30px 0; 
            page-break-inside: avoid;
            clear: both;
            padding: 15px;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            background: #fff;
          }
          .question-header { 
            font-weight: bold; 
            margin-bottom: 12px; 
            font-size: 18px;
            color: #333;
          }
          .context {
            font-style: italic;
            color: #666;
            margin-bottom: 12px;
            padding: 12px;
            background: #f9f9f9;
            border-left: 4px solid #ddd;
            border-radius: 4px;
          }
          .options { 
            margin-left: 20px;
            line-height: 1.8;
          }
          .option { 
            margin: 10px 0;
            display: block;
          }
          .option-letter {
            font-weight: bold;
            margin-right: 8px;
            color: #3f51b5;
          }
          .answer-line {
            margin-top: 20px;
            border-bottom: 2px dotted #ccc;
            min-height: 28px;
            padding: 5px 0;
            font-weight: bold;
            color: #333;
          }
          .warning {
            color: #d32f2f;
            font-weight: bold;
            background: #ffebee;
            padding: 10px;
            border-radius: 5px;
            text-align: center;
            margin: 20px 0;
            border: 1px solid #ffcdd2;
          }
          .answer-grid {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 12px;
            margin: 25px 0;
            padding: 20px;
            border: 2px solid #d32f2f;
            border-radius: 8px;
            background: #fff;
          }
          .answer-item {
            text-align: center;
            font-weight: bold;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            background: #f5f5f5;
          }
          .question-number {
            font-size: 14px;
            color: #777;
          }
          .detailed-answers {
            margin-top: 40px;
          }
          .section-title {
            font-size: 22px;
            font-weight: bold;
            color: #333;
            border-bottom: 2px solid #3f51b5;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .question-answer { 
            margin: 20px 0; 
            padding: 20px;
            border-left: 5px solid #4caf50;
            background: #f1f8e9;
            border-radius: 8px;
            page-break-inside: avoid;
          }
          .question-text { 
            font-weight: bold; 
            margin-bottom: 12px; 
            font-size: 18px;
            color: #333;
          }
          .correct-answer { 
            color: #2e7d32; 
            font-weight: bold;
            font-size: 16px;
            margin: 10px 0;
          }
          .explanation { 
            margin-top: 12px; 
            font-style: italic; 
            color: #555;
            padding: 12px;
            background: #e8f5e9;
            border-radius: 4px;
          }
          .footer { 
            margin-top: 40px; 
            text-align: center; 
            font-size: 12px;
            color: #888;
            border-top: 1px solid #eee;
            padding-top: 15px;
          }
        </style>
      </head>
      <body>
        <div class="watermark">QuizAi</div>
        
        <!-- QUIZ SHEET SECTION -->
        <div class="header">
          <div class="title">${quizTitle}</div>
          <div class="info">Date: ${date}</div>
          <div class="info">Total Questions: ${questions.length}</div>
          <div class="info">Name: _____________________________________________________________________ Class: ________________  Date: ________________ </div>
        </div>
        
        <div class="instructions">
          <strong style="font-size: 18px; color: #3f51b5;">Instructions:</strong>
          <ul style="margin: 15px 0; padding-left: 20px;">
            <li style="margin-bottom: 8px;">Read each question carefully</li>
            <li style="margin-bottom: 8px;">Choose the best answer for each multiple choice question</li>
            <li style="margin-bottom: 8px;">Mark your answer clearly</li>
            <li>Use the answer line provided for each question</li>
          </ul>
        </div>
        
        ${questions
					.map(
						(question, index) => `
          <div class="question">
            <div class="question-header">
              ${index + 1}. ${question.question}
            </div>
            ${
							question.context
								? `<div class="context">${question.context}</div>`
								: ''
						}
            <div class="options">
              ${
								question.options
									?.map(
										(option, optionIndex) =>
											`<div class="option">
                  <span class="option-letter">${String.fromCharCode(
										65 + optionIndex
									)}.</span> ${option}
                </div>`
									)
									.join('') || ''
							}
            </div>
            <div class="answer-line">
              Answer: _________________________________________
            </div>
          </div>
        `
					)
					.join('')}
        
        <!-- ANSWER KEY SECTION -->
        <div class="page-break">
          <div class="header">
            <div class="title answer-key-title">${quizTitle} - Answer Key</div>
            <div class="info">Date: ${date}</div>
            <div class="info">Total Questions: ${questions.length}</div>
            <div class="warning">⚠️ TEACHER'S ANSWER KEY - DO NOT DISTRIBUTE TO STUDENTS ⚠️</div>
          </div>
          
          <div class="answer-grid">
            ${questions
							.map(
								(question, index) => `
              <div class="answer-item">
                <div class="question-number">${index + 1}</div>
                ${String.fromCharCode(65 + question.correctAnswer)}
              </div>
            `
							)
							.join('')}
          </div>
          
          <div class="detailed-answers">
            <div class="section-title">Detailed Answers & Explanations</div>
            ${questions
							.map(
								(question, index) => `
              <div class="question-answer">
                <div class="question-text">
                  ${index + 1}. ${question.question}
                </div>
                <div class="correct-answer">
                  ✅ Correct Answer: ${String.fromCharCode(
										65 + question.correctAnswer
									)}. ${question.options[question.correctAnswer]}
                </div>
                ${
									question.explanation
										? `
                  <div class="explanation">
                    💡 Explanation: ${question.explanation}
                  </div>
                `
										: ''
								}
              </div>
            `
							)
							.join('')}
          </div>
          
          <div class="footer warning">
            ⚠️ TEACHER'S ANSWER KEY - DO NOT DISTRIBUTE TO STUDENTS ⚠️<br>
            Generated by QuizAi on ${new Date().toLocaleString()} | www.quizai.com
          </div>
        </div>
      </body>
      </html>
    `;

		const printWindow = window.open('', '_blank');
		printWindow.document.write(htmlContent);
		printWindow.document.close();

		setTimeout(() => {
			printWindow.print();
		}, 500);
	},
};

export default CombinedPDFGenerator;
